[project]
name = "tuw-sna"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas==2.2.3",
    "matplotlib==3.9.2",
    "scipy==1.13.1",
    "scikit-learn==1.4.2",
    "jupyter==1.0.0",
    "numpy==2.1.2",
    "seaborn==0.13.2",
]
